print("***********************Marklist for 10 th ************")
print("Please Enter your marks:")
E10=int(input("English:"))
T10=int(input("Tamil:"))
M10=int(input("Maths:"))
S10=int(input("Science:"))
So10=int(input("Social:"))
Total=E10+T10+M10+S10+So10
tenth=(Total/5)
print("____________________________________________________")
print("SUBJECT          |    MARKS")
print("------------------------------------------------------------------------------")
print("English             :  ",E10)
print("Tamil                :  ",T10)
print("Maths              :  ",T10)
print("Science            :  ",T10)
print("Social               :  ",T10)
print("Total Marks   :  ",Total)
print("Percentage    :  ",tenth,"%")
print("***********************Marklist for 12 th ************")
print("Please Enter your marks:")
E1=int(input("English paper1:"))
E2=int(input("English paper2:"))
T1=int(input("Tamil paper1:"))
T2=int(input("Tamil paper2:"))
M1=int(input("Maths paper1:"))
M2=int(input("Maths paper2:"))
P12=int(input("Physics:"))
C12=int(input("Chemistry:"))
B1=int(input("Botany:"))
B2=int(input("Zoology:"))
Lab1=int(input("Lab I:"))
Lab2=int(input("Lab II:"))
#Calculate Total and percentage 
Total12=E1+E2+T1+T2+M1+M2+P12+C12+B1+B2+Lab1+Lab2
twelth=(Total12/12)
print("____________________________________________________")
print("SUBJECT          |    MARKS")
print("------------------------------------------------------------------------------")
print("English I           :  ",E1)
print("English II         :  ",E2)
print("Tamil     I          :  ",T1)
print("Tamil    II         :  ",T2)
print("Maths   I          :  ",M1)
print("Maths   II        :  ",M2)
print("Physics            :  ",P12)
print("Chemistry       :  ",C12)
print("Botany             :  ",B1)
print("Zoology           :  ",B2)
print("Lab     I             :  ",Lab1)
print("Lab     II            :  ",Lab2)
print("Total Marks   :  ",Total12)
print("Percentage    :  ",twelth,"%")
print("--------------------------------------------------------------------------------")
