print("**************PERSONAL INFORMATION ****************")
Name=input("Enter your Name :" )
Mail=input("Enter your Mail id :")
Bank_name=input("Enter your Bank Name:")
IFSC_code=input("Enter your IFSC Code:")
Balance=float(input("Enter your Bank Balance:"))
print("***************BANK DETAILS***********************************")
print("NAME            : " ,Name)
print("MAIL ID         : ",Mail)
print("BANK NAME       : ",Bank_name)
print("IFSC CODE       : ",IFSC_code)
print("BALANCE         : ",Balance)
print("*************************************************************")
